#!/usr/bin/perl
use strict;
use warnings;

my $code = "NICKATARI";
my $sum = 0;
$sum += ord($_) for $code =~ /(.)/g;
my $magic = 0x0296;

my @header = (
0x96, 0x02, # magic
#0xe8, 0x2c, # num paragraphs
#0x00, 0x01, # sector size
0xd0, 0x59, # num paragraphs
0x80, 0x00, # sector size
0x00,       # extended paragraphs
0x00, 0x00, 0x00, 0x00, # 32 bit authentication crc
0x00, 0x00, 0x00, 0x00, # unused
0x00,       # bit 0: write protect
            # bit 1: sealed/authenticated atr
            # bit 2..7: unused
);

my $header = pack "C16", @header;

my $data = join '', <>;

print $header, $data;

print "\0" x (183936 - length $data);
